---
- name: Install qemu-guest-agent package
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Install python3-apt
      ansible.builtin.apt:
      name: python3-apt
      state: present
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
