---
- hosts: all
  tasks:
  - name: update using dnf
    become: true 
    ansible.builtin.dnf:
      update_cache: true
      name: "*"
      state: latest
    when: ansible_pkg_mgr == 'dnf'

  - name: update using apt
    become: true
     become_user: root
     become_method: sudo
    ansible.builtin.apt:
      update_cache: true
      name: "*"
      state: latest
    when: ansible_pkg_mgr == 'apt'
...
